### ISSUE TITLE
(ACCIDENTALLY MADE A DUPLICATE OF AN ALREADY EXISTING ISSUE)

### ISSUE THREAD

**Issue by queenkoopa8500** [loophole/cli#266] opened 2024-06-08 23:06 UTC
accidentally made a duplicate of an already existing issue which is #249

**Comment by uuphoria2** [comment] 2024-06-09 19:49
@Morishiri can you or anybody help me on this issue please?

**Comment by uuphoria2** [comment] 2024-06-09 22:10
this issue is already at #249 closing this

**Comment by uuphoria2** [comment] 2024-06-09 22:11
accidentally made a duplicate of somebodys already existing issue: #249 go to that issue page instead, loophole team incase you look at this issue (this current one aka #266) instead of #249

**Closed as completed** 2024-06-09 22:10 UTC
Labels: bug

**Comment by uuphoria2** [comment] 2024-06-09 22:11
#249 accidentally made a duplicate of this

**Comment by uuphoria2** [comment] 2024-06-10 03:13
this is a duplicate of #249 (accidental) go to issue #249 instead for anyone viewing this
